### ISSUE TITLE
I'm missing a native binary

### ISSUE THREAD

**Issue by Gansgar** [refactorsaurusrex/journal-cli#60]
The script says, that it's missing a native git binary and the FAQ redirected me here.

I'm on an Ubuntu 20.04 with Powershell 7 if that helps.

**Comment by refactorsaurusrex** [comment]
Hey @Gansgar... thanks for reporting this. I'll look at it today.

**Comment by Gansgar** [comment]
Wow. That's a response time.

But hey that's great ^^

**Comment by refactorsaurusrex** [comment]
> Wow. That's a response time.

I happened to be sitting at my computer when this came in. 😄 

So it looks like Ubuntu [20.04 isn't officially supported by PowerShell](https://github.com/PowerShell/PowerShell/issues/12626). Did you install it using `sudo snap install powershell --classic`? That's what I did to repro the problem on my vm, although it still seems like it should be working. The native binary is actually there, so I'm not sure why it's failing. I'm going to add some additional logging and see what specific messages I get.

**Comment by refactorsaurusrex** [comment]
[Here's the solution.](https://github.com/libgit2/libgit2sharp/issues/1747#issuecomment-606033076) Problem now is that the build currently dumps all native binaries in the same directory, and I need to retain the output of targeting both `ubuntu.18.04-x64` and `linux-x64`. Both have the same name but (apparently) different contents. 

For future reference, here is the error that was generated:
```
2020-05-25 14:48:33.447 -05:00 [ERR] Error encountered during Commit()
System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'git2-106a5f2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgit2-106a5f2: cannot open shared object file: No such file or directory
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_repository_open_ext(git_repository*& repository, FilePath path, RepositoryOpenFlags flags, FilePath ceilingDirs)
   at LibGit2Sharp.Core.Proxy.git_repository_open_ext(String path, RepositoryOpenFlags flags, String ceilingDirs)
   at LibGit2Sharp.Repository.IsValid(String path)
   at JournalCli.Cmdlets.JournalCmdletBase.ValidateGitRepo()
   at JournalCli.Cmdlets.JournalCmdletBase.Commit(GitCommitType commitType)
```

**Comment by Gansgar** [comment]
Thanks a lot. I'll try it again when I'm booting into Ubuntu. And yes, I installed it through snap.

**Comment by refactorsaurusrex** [comment]
Well, I still need to get the change built into `journal-cli`. :) It's a little hacky because dotnet doesn't seem to provide a precise way to distinguish between Ubuntu releases. 

In the meantime, I can give you the correct binary and tell you where to put it, if you'd like. I'll upload it here when I get back to my personal machine.

**Comment by refactorsaurusrex** [comment]
Notes to self: 
- https://github.com/PowerShell/PowerShell/issues/8861
- https://github.com/PowerShell/PowerShell/pull/11032

**Comment by refactorsaurusrex** [comment]
@Gansgar If you drop [this file](https://user.fm/files/v2-c939dbfcbb120bf0a8cd39c3614c8b3d/libgit2-106a5f2.so) in `/home/{username}/.local/share/powershell/Modules/JournalCli/{version}`, it should resolve your issue while I work on a proper fix. You'll know it's fixed if a `.git` directory appears in your journal's root directory after running a command such as `New-JournalEntry`.

**Comment by Gansgar** [comment]
Wow thanks. That worked.

**Comment by refactorsaurusrex** [comment]
Not fixed. :(

**Comment by refactorsaurusrex** [comment]
I have a solution for this, just haven't had time to wrap it up. It will be done within a couple of weeks. I've been avoiding it because its been a real pain in the ass.

**Comment by lboening** [comment]
@refactorsaurusrex  Unfortunately, I encountered the identical error on Debian 10.7. The approach you mentioned above in the May 25 solution--to copy the lib.git.so such and such file into the local journal folder--did not alone help. I then entered that folder and ran a "git init" command. An empty ".git" folder now exists. But, I still get the error.

**Comment by refactorsaurusrex** [comment]
Thanks for that info @lboening. I suspect this problem affects most Linux distros. I'm still fiddling with a solution that doesn't involve creating a massively bloated module package.

**Comment by refactorsaurusrex** [comment]
I never did find a satisfying solution to distributing native binaries like this, so I'm going the complete opposite direction: I'm completely ripping out the git integration. Instead, I'm building end to end encrypted synchronization to S3 which will take advantage of S3's object versioning. The upside of doing this is you'll be able to access your journal from any internet-connected machine; the downside is that you have to opt in to cloud sync in order to enable versioning of your journal which, of course, entails some risk.
